# Generated by Django 6.0.2 on 2026-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.TextField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('cover', models.ImageField(upload_to='')),
            ],
        ),
    ]
