# Generated by Django 6.0.2 on 2026-03-03 12:59

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fantasy', 'Fantasy'), ('dark_fantasy', 'Dark_Fantasy'), ('action', 'Action'), ('adventure', 'Adventure'), ('shonen', 'Shonen'), ('horror', 'Horror'), ('sci_fi', 'Sci_Fi'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('historical', 'Historical'), ('drama', 'Drama'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('poetry', 'Poetry'), ('biography', 'Biography'), ('manga', 'Manga')], max_length=140),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('paperbook', 'Paperbook'), ('e_book', 'E-Book'), ('audiobook', 'Audiobook')], max_length=30),
        ),
    ]
